defaults:
  - logger: base_logger
  - arch: anakin
  - system: rec_ppo
  - network: rnn
  - env: gymnax/cartpole
  - _self_

hydra:
  searchpath:
    - /root/enzyme-of-computation/.venv/src/stoix/stoix/configs
