defaults:
  - logger: base_logger
  - arch: anakin
  - system: rec_ppo
  - network: rnn
  - env: gymnax/cartpole
  - _self_

hydra:
  searchpath:
    - /Users/jan/repos/enzyme-of-computation/Stoix/stoix/configs
